const fs=require('fs'),path=require('path'),os=require('os');
const base=process.cwd(),out=path.resolve(__dirname,'..'),assets=path.join(out,'composition/assets');fs.mkdirSync(assets,{recursive:true});
const cache=path.join(os.homedir(),'.npm/_npx');const modules=fs.readdirSync(cache).map(d=>path.join(cache,d,'node_modules')).find(d=>fs.existsSync(path.join(d,'hyperframes/package.json'))&&fs.existsSync(path.join(d,'esbuild/package.json')));
const esbuild=require(path.join(modules,'esbuild')),puppeteer=require(path.join(modules,'puppeteer-core'));
const chromeCache=path.join(os.homedir(),'.cache/puppeteer/chrome-headless-shell');const executablePath=fs.readdirSync(chromeCache).filter(d=>d.startsWith('mac_arm-')).sort().reverse().map(d=>path.join(chromeCache,d,'chrome-headless-shell-mac-arm64/chrome-headless-shell')).find(fs.existsSync);
const imports=`import {renderHome} from './home';import {renderOptApply} from './pages/opt-apply';import {renderStemApply} from './pages/stem-apply';import {renderClock} from './pages/clock';import {renderStemClock} from './pages/stem-clock';import {buildThemeCss} from './design/theme-css';import * as widget from './job-portal-tracker-widget';import {paintResumeStatusRow} from './resume-status-row';import {runPrefill} from './easy-apply-engine';import {resolveAutofillPlanEntitlements} from './autofill-plan-entitlements';window.demo={paintResumeStatusRow,renderHome,renderOptApply,renderStemApply,renderClock,renderStemClock,buildThemeCss,widget,runPrefill,resolveAutofillPlanEntitlements};`;
const manifest=process.env.JOB_ONLY?JSON.parse(fs.readFileSync(path.join(out,'capture-manifest.json'))).filter(x=>x.width===360):[];const delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const bundle=await esbuild.build({stdin:{contents:imports,resolveDir:path.join(base,'apps/extension/src'),loader:'ts'},define:{'process.env.EXT_TARGET':'"test"','process.env.NODE_ENV':'"test"'},bundle:true,write:false,format:'iife',platform:'browser'});
 const browser=await puppeteer.launch({executablePath,headless:true,args:['--disable-dev-shm-usage']});
 try{const page=await browser.newPage();page.setDefaultTimeout(8000);page.on('pageerror',e=>console.error('PAGEERROR',e.message));await page.setViewport({width:360,height:650,deviceScaleFactor:2});
 await page.setRequestInterception(true);page.on('request',req=>req.url().startsWith('data:')?req.continue():req.respond({status:200,contentType:'text/html',body:'<html><body><div id="root"></div></body></html>'}));await page.goto('https://demo.example.test/');
 await page.evaluate(logo=>{const RealDate=Date;window.Date=class extends RealDate{constructor(...a){super(...(a.length?a:['2026-09-26T16:00:00Z']));}static now(){return new RealDate('2026-09-26T16:00:00Z').getTime();}};window.store={theme:'light'};window.saved={};window.posts=[];window.messages=[];const storage={get:async k=>typeof k==='string'?{[k]:window.store[k]}:window.store,set:async p=>Object.assign(window.store,p),remove:async()=>{}};
 window.chrome={storage:{local:storage,sync:storage,onChanged:{addListener:()=>{}}},runtime:{getURL:()=>logo,onMessage:{addListener:()=>{}},sendMessage:(m,cb)=>{window.messages.push(m);let r={ok:true};if(m.type==='CHECK_JOB_SAVED')r.saved=false;if(m.type==='ADD_JOB_TO_TRACKER')r={ok:true,id:'demo-job',status:m.status};if(m.type==='OPEN_SIDE_PANEL')r.ok=false;if(m.type==='LIST_SAVED_RESUMES')r={ok:true,resumes:[{id:'demo-resume',filename:'Alex_Taylor_Resume.pdf'}],accountEmail:'alex@example.test'};if(m.type==='ANALYZE_JOB_FIT')r={ok:true,matchScore:75,matchedKeywords:['SQL','Python','Data analysis'],missingKeywords:['Tableau'],gapSummary:'Add relevant Tableau experience only if it is accurate.',resumeName:'Alex_Taylor_Resume.pdf'};if(m.type==='GENERATE_RESUME')r={ok:true,pdfBase64:'JVBERi0xLjQKJSBEZW1v',filename:'Alex_Taylor_Data_Analyst.pdf',editorUrl:'https://demo.example.test/editor',artifact:{artifactId:'demo-artifact',generatedContentHash:'demo',pdf:{filename:'Alex_Taylor_Data_Analyst.pdf',base64:'JVBERi0xLjQK'}}};if(m.type==='GENERATE_COVER_LETTER')r={ok:true,attachment:{base64:'JVBERi0xLjQK',filename:'Alex_Taylor_Cover_Letter.pdf'},draftText:'Dear Example Corp team,\n\nI am interested in the Junior Data Analyst role. My project experience includes using SQL and Python to explore data and communicate findings. I would welcome the opportunity to contribute to your analytics team.\n\nSincerely,\nAlex Taylor'};if(cb)setTimeout(()=>cb(r),100);return Promise.resolve(r);}},tabs:{query:async()=>[]}};
 window.fetch=async(url,opt={})=>{let data={};if(opt.method==='POST'){const p=JSON.parse(opt.body||'{}');window.posts.push(p);Object.assign(window.saved,p);}if(String(url).includes('calculator')){data={ok:true,data:{opt_ead_end_date:null,stem_dso_recommendation_date:null,...window.saved,...(Object.keys(window.saved).length?{unemployment_clock:{active:true,used:20,max:window.phase==='stem'?150:90,remaining:window.phase==='stem'?130:70,phase:window.phase==='stem'?'stem':'initial'}}:{})}};}else if(String(url).includes('premium/status'))data={isPremium:true,planName:'pro'};else if(String(url).includes('tool-email'))data={email:'alex@example.test'};else if(String(url).includes('case-status'))data={data:{receipt_number:'DEMO CASE',filing_category:'opt',current_status:'Case Was Received'},cases:[{}]};return{ok:true,json:async()=>data};};window.open=()=>null;},'data:image/png;base64,'+fs.readFileSync('apps/extension/public/icons/icon128.png').toString('base64'));
 await page.addScriptTag({content:bundle.outputFiles[0].text});await page.addStyleTag({content:await page.evaluate(()=>demo.buildThemeCss())});await page.addStyleTag({content:fs.readFileSync('apps/extension/public/popup.css','utf8')});
 await page.evaluate(()=>{window.openHome=async()=>{window.scrollTo(0,0);await demo.renderHome(document.getElementById('root'),async route=>{window.route=route;window.saved={};const fn={'opt-apply':'renderOptApply','clock':'renderClock','stem-apply':'renderStemApply','stem-clock':'renderStemClock'}[route];window.phase=route.includes('stem')?'stem':'initial';if(fn)await demo[fn](document.getElementById('root'),window.openHome);});};});
 async function shot(name,selector,clip){await delay(450);await page.mouse.move(1,1);let target=null;if(selector){await page.$eval(selector,e=>e.scrollIntoView({block:'nearest'}));await delay(100);target=await page.$eval(selector,e=>{const r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2};});}await page.screenshot({path:path.join(assets,name+'.png'),...(clip?{clip}:{})});manifest.push({name,width:clip?.width||page.viewport().width,height:clip?.height||page.viewport().height,target:target?{x:target.x-(clip?.x||0),y:target.y-(clip?.y||0)}:null});fs.writeFileSync(path.join(out,'capture-manifest.json'),JSON.stringify(manifest,null,2));console.log(name);}
 async function clickText(text){await page.evaluate(t=>{const buttons=[...document.querySelectorAll('button')];const el=buttons.find(e=>e.textContent.trim()===t)||buttons.find(e=>e.textContent.includes(t));if(!el)throw Error('Missing button '+t);el.click();},text);await delay(400);}
 async function fill(sel,val){await page.$eval(sel,(e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));},val);}
 if(!process.env.JOB_ONLY){await page.evaluate(()=>openHome());await shot('home','[data-page="clock"]');
 for(const [route,input,value,name]of[['clock','#opt-start-date','09/06/2026','opt-clock'],['stem-clock','#stem-ead-start-date','09/06/2026','stem-clock'],['opt-apply','#program-end-date','10/15/2026','opt-filing'],['stem-apply','#current-opt-end-date','12/15/2026','stem-filing']]){
 await page.evaluate(()=>openHome());await shot(name+'-nav',`[data-page="${route}"]`);await page.click(`[data-page="${route}"]`);await shot(name+'-empty',input);
 if(name==='opt-clock'){await page.click('#start-date-picker-btn');await shot('opt-calendar');await page.keyboard.press('Escape');await page.mouse.click(350,100);}
 await fill(input,value);if(name==='opt-filing')await fill('#dso-recommendation-date','09/25/2026');if(name==='stem-filing')await fill('#stem-dso-recommendation-date','09/25/2026');await shot(name+'-filled','.tool-button-primary');await clickText(name.includes('filing')?'Calculate Filing Window':'Save & Go');await shot(name+'-result');
 if(name==='opt-clock'){await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));await shot('opt-reminders');}
 }
 await page.evaluate(()=>openHome());await page.evaluate(()=>window.scrollTo(0,420));await shot('home-settings','#prefill-mode-continuous');await page.click('#prefill-mode-continuous');await shot('continuous','#guided-autopilot-toggle');await page.click('#guided-autopilot-toggle');await shot('guided');}
 await page.evaluate(()=>{document.querySelectorAll('style').forEach(e=>e.remove());document.body.innerHTML='<main id="job"></main>';document.body.className='';});await page.setViewport({width:1000,height:680,deviceScaleFactor:2});
 await page.addStyleTag({content:`body{margin:0;background:#f6f8fb;color:#0f172a;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}main{box-sizing:border-box;margin:24px;width:530px;padding:28px;background:white;border:1px solid #e2e8f0;border-radius:16px}h1{font-size:26px;margin:12px 0}h2{font-size:21px}p{font-size:14px;line-height:1.55;color:#475569}.fields{display:grid;grid-template-columns:1fr 1fr;gap:16px}label{font-size:13px;font-weight:600;display:block}input,select{box-sizing:border-box;display:block;width:100%;padding:10px;margin-top:6px;border:1px solid #cbd5e1;border-radius:7px;background:white;font-size:15px;color:#0f172a}.wide{grid-column:1/-1}.tag{font-size:11px;letter-spacing:1px;color:#2563eb;font-weight:700}button{font-family:inherit}.submit{margin-top:20px;padding:10px 24px;border:0;border-radius:7px;background:#0f172a;color:white}#job-description{display:none}`});
 await page.evaluate(()=>{const jd='Example Corp is hiring a Junior Data Analyst in Boston. Use SQL and Python to prepare reports and analyze data. Collaborate with the analytics team to create Tableau dashboards. Explain findings clearly to stakeholders. This is a fictional posting used for a product demonstration. Candidates should have project experience in data analysis and data visualization.';window.job={role_title:'Junior Data Analyst',company_name:'Example Corp',job_url:location.href,location:'Boston, MA',job_description:jd};document.getElementById('job').innerHTML=`<span class="tag">EXAMPLE CORP · SAMPLE APPLICATION</span><h1>Junior Data Analyst</h1><p>Boston, MA · Data & analytics</p><form id="application-form"><h2>Your application</h2><div class="fields"><label>First name<input name="first_name"></label><label>Last name<input name="last_name"></label><label class="wide">Email<input name="email" type="email"></label><label>Country<select name="country"><option value="">Select country</option><option value="US">United States</option></select></label><label>City<input name="city"></label><label class="wide">Will you need visa sponsorship?<select name="visa_sponsorship"><option value="">Select your answer</option><option>Yes</option><option>No</option></select></label><label class="wide">Resume<input type="file" name="resume" aria-label="Resume"></label></div><button class="submit" type="button">Submit application</button></form><div id="job-description">${jd}</div>`;
 const noop=()=>{};demo.widget.setJobTrackerWidgetHost({undoLastPrefill:async()=>({restored:0}),trackWidgetAnalytics:noop,trackWidgetAnalyticsOnce:noop,getArtifactStaleReason:()=>null,rememberTrackerApplicationId:noop,trackerApplicationIdFor:()=>undefined,reconcileArtifactAvailabilityOnWidgetMount:async()=>{},generatedResumeFor:()=>undefined,executeResolvedPrefill:async()=>({result:await demo.runPrefill({profileFallback:{firstName:'Alex',lastName:'Taylor',email:'alex@example.test',country:'US',city:'Boston'},quietResultToast:true}),hasResume:false,hasCoverLetter:false,sourceType:'profile',artifactStateReason:'none'}),trackPrefillExecution:noop,trackPrefillRuntimeFailure:noop,mountScreeningQuestionReviews:async()=>{},markPostSaveSuggestionSeen:async()=>true,paintGuidedStateUi:noop,stopGuidedAutopilot:async()=>{},setCurrentGeneratedArtifact:noop,markCurrentArtifactInvalid:noop,getPlanEntitlements:()=>demo.resolveAutofillPlanEntitlements('pro'),scheduleInject:noop});const widget=demo.widget.createJobTrackerWidget(window.job,'expanded');document.body.appendChild(widget);demo.paintResumeStatusRow(widget.querySelector('.tmo-resume-status-row'),'none');window.card=widget.querySelector('.tmo-job-widget-card');});
 await shot('job-before','.tmo-prefill-button');await page.click('.tmo-prefill-button');await shot('job-filled');
 await shot('job-save','.tmo-sidebar-tracker');await page.click('.tmo-sidebar-tracker');await shot('job-status');await clickText('I have not applied yet');await shot('job-saved');
 await shot('job-analyze','.tmo-analysis-button');await page.click('.tmo-analysis-button');await delay(800);await shot('job-analysis');
 await page.keyboard.press('Escape');await shot('job-resume','.tmo-resume-button');await page.click('.tmo-resume-button');await delay(800);await shot('resume-chooser');await clickText('Generate');await delay(700);await page.$eval('.tmo-job-widget-scroll-body',e=>e.scrollTop=e.scrollHeight);await shot('resume-ready');await clickText('Generate cover letter');await page.$eval('.tmo-job-widget-scroll-body',e=>e.scrollTop=e.scrollHeight);await page.evaluate(()=>[...document.querySelectorAll('.tmo-cover-letter-review button')].find(e=>e.textContent==='Edit').click());await shot('cover-letter');await page.click('[aria-label=\"Private answers (included in Prefill)\"]');await shot('private-answers','[aria-label=\"Private answers (included in Prefill)\"]');await page.click('[aria-label=\"Settings\"]');await shot('widget-settings');
 fs.writeFileSync(path.join(out,'capture-manifest.json'),JSON.stringify(manifest,null,2));fs.writeFileSync(path.join(out,'capture-evidence.json'),JSON.stringify(await page.evaluate(()=>({posts:window.posts,messages:window.messages,fields:[...document.querySelectorAll('#application-form input,#application-form select')].map(e=>({name:e.name,value:e.value}))})),null,2));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
