// Adapted browser-device-stage and logo-brand-close choreography.
// All source UI remains intact; this script stages it in an aluminum laptop shell.
const fs=require('fs'),path=require('path');
const out=path.resolve(__dirname,'..'),comp=path.join(out,'composition');
const source=fs.readFileSync(path.join(out,'base-composition.html'),'utf8');
const style=source.match(/<style>([\s\S]*?)<\/style>/)[1];
let body=source.match(/<body><div[^>]*data-composition-id="main"[^>]*>([\s\S]*)<\/div><script>/)[1];
const audios=[...body.matchAll(/<audio\b[^>]*>.*?<\/audio>/g)].map(m=>m[0]);
body=body.replace(/<audio\b[^>]*>.*?<\/audio>/g,'');
body=body.replace(/data-start="([\d.]+)"/g,(_,n)=>`data-start="${(4.5+Number(n)*80/90).toFixed(6)}"`)
 .replace(/data-duration="([\d.]+)"/g,(_,n)=>`data-duration="${(Number(n)*80/90).toFixed(6)}"`);
let animation=source.match(/<script>const tl=([\s\S]*?)<\/script>/)[1];
animation=('const demoTl='+animation).replace('gsap.timeline({paused:true})','gsap.timeline()').replace(/\btl\./g,'demoTl.');
animation=animation.split('window.__timelines=')[0];
const clicks=audios.filter(s=>/id="click/.test(s)).map(s=>s.replace(/data-start="([\d.]+)"/,(_,n)=>`data-start="${(4.5+Number(n)*80/90).toFixed(6)}"`)).join('\n');
const letters=[...'TrackMyOPT'].map(c=>`<span class="brand-letter">${c}</span>`).join('');
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Introducing TrackMyOPT for Chrome</title><script src="assets/gsap.min.js"></script><style>${style}
html,body{background:#e8edf7}#root{perspective:2200px}.atmosphere{position:absolute;inset:0;overflow:hidden;background:radial-gradient(ellipse at 20% 18%,#f9fbff 0%,#e4edff 38%,#d5e1f5 70%,#c2cfe5 100%)}.halo{position:absolute;border:2px solid rgba(255,255,255,.65);border-radius:50%;width:1900px;height:1300px;left:-640px;top:-540px}.halo.second{left:780px;top:380px;width:1600px;height:1000px;border-color:rgba(70,107,165,.12)}.floor{position:absolute;left:160px;top:938px;width:1600px;height:130px;background:radial-gradient(ellipse,rgba(31,51,90,.28),transparent 65%)}
.laptop{position:absolute;left:140px;top:48px;width:1640px;height:950px;transform-style:preserve-3d;transform-origin:50% 50%}.lid{position:absolute;inset:0;border-radius:32px 32px 16px 16px;background:linear-gradient(135deg,#e3e6ec,#929dac 38%,#e5e8ed 60%,#9ca7b5);padding:4px;box-shadow:0 24px 70px rgba(29,48,83,.25)}.bezel{position:absolute;inset:4px;border-radius:28px 28px 13px 13px;background:#141922}.camera{position:absolute;top:11px;left:816px;width:7px;height:7px;border-radius:50%;background:#33445b;z-index:5}.screen{position:absolute;left:20px;top:27px;width:1600px;height:900px;overflow:hidden;border-radius:10px;background:#f6f8fb}.demo-content{position:absolute;width:1920px;height:1080px;left:0;top:0;transform:scale(.8333333333);transform-origin:0 0;overflow:hidden}.base{position:absolute;left:-60px;top:947px;width:1760px;height:33px;border-radius:2px 2px 70px 70px;background:linear-gradient(#edf0f4,#b9c2cf 30%,#7d899b 82%,#d2d8e2);box-shadow:0 17px 30px rgba(29,48,83,.22)}.lip{position:absolute;left:730px;top:947px;width:180px;height:12px;border-radius:0 0 16px 16px;background:#95a0b1;z-index:2}
.hero-screen{position:absolute;inset:0;background:radial-gradient(ellipse at 10% 10%,#e3edff,transparent 70%),#f6f8fb}.hero-lockup{position:absolute;left:94px;top:214px;width:760px}.hero-icon{width:112px;height:112px;border-radius:26px;box-shadow:0 20px 35px rgba(37,99,235,.16)}.hero-lockup h2{font-size:76px;letter-spacing:-3px;line-height:1.1;margin:34px 0 22px;color:#0f172a}.hero-lockup p{font-size:28px;color:#475569;margin:0;line-height:1.5}.hero-ui{position:absolute;left:950px;top:68px;width:560px;height:764px;overflow:hidden;border:2px solid #dce3ee;border-radius:24px;box-shadow:0 24px 50px rgba(30,54,96,.16)}.hero-ui img{width:560px;height:auto;display:block}
.intro-copy{position:absolute;left:94px;top:230px;width:750px}.eyebrow{font-size:24px;letter-spacing:5px;font-weight:650;color:#1e40af;margin:0 0 26px}.intro-copy h2{font-size:96px;line-height:1.06;letter-spacing:-5px;margin:0 0 28px;color:#0f172a;white-space:nowrap}.brand-letter{display:inline-block}.intro-copy .subtitle{font-size:44px;line-height:1.3;color:#334155;margin:0}.intro-logo{width:92px;height:92px;border-radius:22px;margin-bottom:32px}.intro-line{height:5px;width:100px;background:#2563eb;margin-top:37px;transform-origin:left center}.outro-copy{position:absolute;left:1000px;top:255px;width:820px}.outro-copy h2{font-size:83px;line-height:1.1;letter-spacing:-4px;margin:0 0 25px;color:#0f172a}.outro-copy p{font-size:38px;color:#334155;margin:0 0 34px;line-height:1.3}.cta{display:inline-flex;align-items:center;gap:25px;background:#2563eb;color:#fff;border-radius:18px;padding:24px 34px;font-size:30px;font-weight:600;box-shadow:0 15px 35px rgba(37,99,235,.2)}.url{font-size:26px!important;letter-spacing:1px;margin-top:25px!important;color:#334155!important}.launch-note{position:absolute;bottom:25px;left:0;width:100%;text-align:center;font-size:20px;color:#475569}
</style></head><body><div id="root" data-composition-id="main" data-width="1920" data-height="1080" data-duration="90" data-fps="30">
<div class="atmosphere"><div class="halo" data-layout-allow-overflow="true"></div><div class="halo second" data-layout-allow-overflow="true"></div></div><div class="floor"></div>
<div class="laptop" id="laptop"><div class="lid"></div><div class="bezel"></div><div class="camera"></div><div class="screen"><div class="hero-screen" id="hero-screen"><div class="hero-lockup"><img class="hero-icon" src="assets/icon128.png" alt="TrackMyOPT logo"><h2>Your OPT tools.<br>Your job tools.</h2><p>Right where you work.<br>TrackMyOPT for Chrome.</p></div><div class="hero-ui"><img data-layout-allow-overflow="true" src="assets/home.png" alt="TrackMyOPT extension OPT tools"></div></div><div class="demo-content" id="demo-content">${body}</div></div><div class="base" data-layout-allow-overflow="true"></div><div class="lip"></div></div>
<section id="intro-scene" class="clip" data-start="0" data-duration="4.5" data-track-index="7"><div class="intro-copy" id="intro-copy"><img class="intro-logo" src="assets/icon128.png" alt="TrackMyOPT"><p class="eyebrow">INTRODUCING</p><h2>${letters}</h2><p class="subtitle">Your Chrome extension.</p><div class="intro-line"></div></div></section>
<section id="outro-scene" class="clip" data-start="84.5" data-duration="5.5" data-track-index="7"><div class="outro-copy" id="outro-copy"><p class="eyebrow">TRACKMYOPT FOR CHROME</p><h2>Thanks for<br>watching.</h2><p>Your next step starts here.</p><div class="cta">Start using TrackMyOPT <span>↗</span></div><p class="url">trackmyopt.com</p></div></section>
<audio id="narration" src="assets/narration.wav" data-start="0" data-duration="90" data-track-index="5" data-volume="1" data-audio-group="voiceover"></audio>
<audio id="music" src="assets/music.mp3" data-start="0" data-duration="90" data-track-index="3" data-volume=".22" data-automation="{&quot;version&quot;:1,&quot;lanes&quot;:[{&quot;target&quot;:&quot;volume&quot;,&quot;points&quot;:[{&quot;t&quot;:0,&quot;v&quot;:0},{&quot;t&quot;:0.5,&quot;v&quot;:0.22},{&quot;t&quot;:88,&quot;v&quot;:0.22},{&quot;t&quot;:90,&quot;v&quot;:0}]}]}"></audio>${clicks}
</div><script>${animation}
const tl=gsap.timeline({paused:true});demoTl.timeScale(90/80);tl.add(demoTl,4.5);
tl.fromTo('#laptop',{x:460,y:115,scale:.5,rotationY:-12,rotationX:5,opacity:0},{x:430,y:100,scale:.54,rotationY:-6,rotationX:2,opacity:1,duration:1.25,ease:'power3.out'},0);
tl.to('#laptop',{x:0,y:0,scale:1,rotationY:0,rotationX:0,duration:1.1,ease:'power3.inOut'},3.4);
tl.fromTo('#demo-content',{opacity:0},{opacity:1,duration:.001},4.5);
tl.to('#hero-screen',{opacity:0,duration:.001},4.5);
tl.fromTo('.intro-logo',{y:35,scale:.8,opacity:0},{y:0,scale:1,opacity:1,duration:.8,ease:'back.out(1.2)'},.1);
tl.fromTo('.eyebrow',{opacity:0,y:16},{opacity:1,y:0,duration:.5,ease:'power2.out'},.18);
tl.fromTo('.brand-letter',{y:65,opacity:0},{y:0,opacity:1,stagger:.045,duration:.75,ease:'expo.out'},.3);
tl.fromTo('.subtitle',{y:24,opacity:0},{y:0,opacity:1,duration:.6,ease:'power3.out'},.85);
tl.fromTo('.intro-line',{scaleX:0},{scaleX:1,duration:.7,ease:'power3.out'},1.05);
tl.to('#intro-copy',{x:-55,opacity:0,duration:.55,ease:'power2.in'},3.35);
tl.to('.halo',{x:90,y:40,rotation:12,duration:90,ease:'none'},0);
tl.to('#demo-content',{opacity:0,duration:.2},84.3);tl.to('#hero-screen',{opacity:1,duration:.2},84.3);
tl.to('#laptop',{x:-440,y:100,scale:.53,rotationY:7,rotationX:2,duration:1.0,ease:'power3.inOut'},84.5);
tl.fromTo('#outro-copy',{x:60,opacity:0},{x:0,opacity:1,duration:.8,ease:'power3.out'},84.65);
tl.fromTo('.cta',{y:25,opacity:0},{y:0,opacity:1,duration:.7,ease:'power3.out'},85.15);
window.__timelines=window.__timelines||{};window.__timelines.main=tl;
</script></body></html>`;
fs.writeFileSync(path.join(comp,'index.html'),html);
const old=JSON.parse(fs.readFileSync(path.join(out,'storyboard.json'),'utf8'));
if(!old.staged){old.scenes.forEach(s=>{s.start=Number((4.5+s.start*80/90).toFixed(6));s.duration=Number((s.duration*80/90).toFixed(6));});old.staged=true;old.intro={start:0,duration:4.5};old.outro={start:84.5,duration:5.5};fs.writeFileSync(path.join(out,'storyboard.json'),JSON.stringify(old,null,2)+'\n');}
const plan=`# TrackMyOPT Chrome Web Store walkthrough\n\nA 90-second, 1920 × 1080 Chrome extension demo. An animated brand introduction and closing frame 42 source-UI scenes inside a persistent laptop presentation. Fictional demo data and illustrative service responses are used.\n\nThe opening introduces TrackMyOPT for Chrome. At 4.5 seconds, the laptop fills the frame and the original feature walkthrough begins with a real prefill interaction. The closing thanks viewers and invites them to start using TrackMyOPT. The cool-blue background, aluminum laptop, logo, and product palette stay consistent.\n\n| Time | Chapter | Real screen | Action |\n|---|---|---|---|\n| 0.0–4.5 | INTRODUCING | TrackMyOPT icon and extension home | Your Chrome extension |\n${old.scenes.map(q=>`| ${q.start.toFixed(1)}–${(q.start+q.duration).toFixed(1)} | ${q.chapter} | ${q.image} | ${q.action} |`).join('\n')}\n| 84.5–90.0 | THANKS FOR WATCHING | TrackMyOPT icon and extension home | Start using TrackMyOPT |\n\nThe source captures come from the actual extension components. A local harness supplies fictional profile, account, calculator, tracker, and AI-service responses. Prefill executes the actual runPrefill engine. Date calculations run in product code at a fixed reference date. Service waits are shortened and labeled. The video does not demonstrate a live account or claim immigration or hiring outcomes. The résumé side panel and in-page cover-letter flow are distinct surfaces.\n`;
fs.writeFileSync(path.join(out,'brag-plan.md'),plan);
console.log('Staged 42 original scenes, 4.5s intro, 5.5s outro; total 90 seconds.');
