import {
    Fuel,
    Gift,
    Sparkles,
    Music,
    Briefcase,
    Wallet,
    type LucideIcon,
} from "lucide-react";
import { ESTIMATED_SAVINGS_USD } from "@/lib/offers/catalog-savings";

// Fuel deal popup content
export interface FuelDeal {
    id: string;
    title: string;
    subtitle: string;
    discount: string;
    description: string;
    benefits: string[];
    terms: string;
    link: string;
    availableStates: string[];
    category: string;
    badge: string;
    badgeColor: string;
    icon: typeof Fuel;
    maxSavings?: string; // e.g., "Save $17.50 on 35 gal"
}

export const FUEL_DEALS: FuelDeal[] = [
    {
        id: "fuel-discount",
        title: "Fuel Savings",
        subtitle: "Bee's Knees Benefits™",
        discount: "$0.50/gal OFF",
        maxSavings: "Save $17.50 on 35 gal",
        description: "Save $0.50 per gallon on fuel, up to 35 gallons per fill-up. That's up to $17.50 in savings every time you fill up!",
        benefits: [
            "$0.50 off per gallon",
            "Up to 35 gallons per transaction",
            "Save up to $17.50 per fill-up",
            "No minimum purchase required",
            "Works at participating locations"
        ],
        terms: "Valid at participating locations. Savings applied at pump with registered account. Maximum 35 gallons per transaction.",
        link: "https://beesknees.myguestaccount.com/en-us/guest/enroll?card-template=gz6U71JdL9Y%3d&template=0",
        availableStates: ["TX", "VA", "NY", "CT", "MA", "RI", "NH", "VT", "ME"],
        category: "Fuel & Gas",
        badge: "Hot Deal",
        badgeColor: "from-amber-500 to-orange-500",
        icon: Fuel,
    },
    {
        id: "weekly-freebees",
        title: "Weekly FreeBees",
        subtitle: "Bee's Knees Benefits™",
        discount: "FREE Items",
        maxSavings: "Free product worth $3-$15",
        description: "Get one FREE item every Wednesday! Enrolled members receive exclusive weekly freebies at participating stores.",
        benefits: [
            "1 FREE item every Wednesday",
            "Products worth $3 to $15",
            "New product each week",
            "Valid 12:00 AM - 11:59 PM EST",
            "While supplies last"
        ],
        terms: "Weekly FreeBees is a program for enrolled, registered, and valid Bee's Knees Benefits™ members. Each offer is valid one day only, Wednesday, between 12:00 AM - 11:59 PM EST, while supplies last. Offer is for one (1) free item per member per week. Use your account at a participating location; to redeem, select YES on the pin pad at POS when prompted. Offer subject to change at any time. Offer valid on participating products only. Offer is non-transferable and cannot be combined with other offers, discounts, or redeemed for cash. Void where prohibited.",
        link: "https://beesknees.myguestaccount.com/en-us/guest/enroll?card-template=gz6U71JdL9Y%3d&template=0",
        availableStates: ["TX", "VA", "NY", "CT", "MA", "RI", "NH", "VT", "ME"],
        category: "Free Rewards",
        badge: "Weekly",
        badgeColor: "from-green-500 to-emerald-500",
        icon: Gift,
    },
];

// Sample offers data - using consistent icons from the project (Sidebar, health insurance page)
export interface Offer {
    id: string;
    title: string;
    description: string;
    discount: string;
    category: string;
    section: "essential" | "tech" | "lifestyle" | "career" | "finance";
    badge: string;
    badgeColor: string;
    logoDomain: string;
    link: string;
}

export const OFFER_SECTIONS: { id: Offer["section"]; title: string; icon: LucideIcon }[] = [
    { id: "tech", title: "Tech & AI Productivity", icon: Sparkles },
    { id: "lifestyle", title: "Lifestyle & Streaming", icon: Music },
    { id: "career", title: "Professional & Career Development", icon: Briefcase },
    { id: "finance", title: "Relocation & Finance", icon: Wallet },
];

/** Top picks for TrackMyOPT users — F-1, OPT, and international students. */
export const FEATURED_OFFER_IDS = [
    "iso-insurance",
    "kimber-health",
    "google-gemini-student",
    "linkedin-student-beans",
    "wise-students",
    "chatgpt-student",
] as const;

export function getFeaturedOffers(offers: Offer[]): Offer[] {
    const byId = new Map(offers.map((offer) => [offer.id, offer]));
    return FEATURED_OFFER_IDS.flatMap((id) => {
        const offer = byId.get(id);
        return offer ? [offer] : [];
    });
}

export const OFFERS: Offer[] = [
    {
        id: "iso-insurance",
        title: "ISO Insurance",
        description: "Get comprehensive health insurance designed for international students and OPT workers.",
        discount: "Starting $38/mo",
        category: "Health Insurance",
        section: "essential",
        badge: "Popular",
        badgeColor: "from-blue-500 to-cyan-500",
        logoDomain: "isoa.org",
        link: "https://www.isoa.org/?ref=trackmyopt",
    },
    {
        id: "kimber-health",
        title: "Kimber Health",
        description: "NY Essential Plan enrollment assistance - $0/month coverage for eligible residents.",
        discount: "FREE for NY",
        category: "Health Insurance",
        section: "essential",
        badge: "Hot Deal",
        badgeColor: "from-orange-500 to-pink-500",
        logoDomain: "kimberhealth.com",
        link: "https://www.kimberhealth.com/",
    },
    {
        id: "chatgpt-student",
        title: "ChatGPT Work for Students",
        description: "4 months of ChatGPT Work free ($80 value) — study guides, docs, quizzes, voice mode, and connected apps. U.S. college students verify via SheerID; claim by Oct 31.",
        discount: "4 Months FREE",
        category: "Tech & AI",
        section: "tech",
        badge: "Limited Time",
        badgeColor: "from-emerald-600 to-teal-700",
        logoDomain: "openai.com",
        link: "https://chatgpt.com/students/2026/",
    },
    {
        id: "google-gemini-student",
        title: "Google AI Pro for Students",
        description: "12 months of Google AI Pro free ($240 value) — 4× Gemini limits, Gemini in Gmail/Docs, study tools, and 5 TB storage. College students 18+ verify via SheerID; US and select global markets.",
        discount: "12 Months FREE",
        category: "Tech & AI",
        section: "tech",
        badge: "Best Value",
        badgeColor: "from-blue-500 to-indigo-600",
        logoDomain: "google.com",
        link: "https://gemini.google.com/students",
    },
    {
        id: "figma-education",
        title: "Figma Education Plan",
        description: "Free Professional tier — unlimited files, team libraries, FigJam, Dev Mode, and version history. K-12 and higher-ed students worldwide; school email verification, no credit card or SSN.",
        discount: "FREE Pro",
        category: "Tech & AI",
        section: "tech",
        badge: "Design",
        badgeColor: "from-fuchsia-500 to-purple-600",
        logoDomain: "figma.com",
        link: "https://www.figma.com/education",
    },
    {
        id: "autodesk-education",
        title: "Autodesk Education Plan",
        description: "Free one-year access to AutoCAD, Fusion, Revit, and more — renewable while enrolled. Post-secondary students 18+ verify via SheerID; educational use only, no SSN required.",
        discount: "1 Year FREE",
        category: "Tech & AI",
        section: "tech",
        badge: "Engineering",
        badgeColor: "from-teal-600 to-cyan-700",
        logoDomain: "autodesk.com",
        link: "https://www.autodesk.com/education/home",
    },
    {
        id: "rowzero-student",
        title: "Row Zero Pro for Students",
        description: "Free Row Zero Pro big-data spreadsheet for U.S. and Canadian students. Sign up with your university email to unlock Pro — ideal for data, finance, and analytics coursework.",
        discount: "FREE Pro",
        category: "Tech & AI",
        section: "tech",
        badge: "Data",
        badgeColor: "from-sky-500 to-blue-700",
        logoDomain: "rowzero.com",
        link: "https://rowzero.com/edu",
    },
    {
        id: "quizplus-ai",
        title: "Quizplus AI Copilot",
        description: "Free AI study assistant with chat help, instant answers, and explanations. Add your university and courses to match your curriculum — no student verification or SSN required.",
        discount: "FREE",
        category: "Tech & AI",
        section: "tech",
        badge: "Study Aid",
        badgeColor: "from-violet-600 to-indigo-700",
        logoDomain: "quizplus.com",
        link: "https://quizplus.com/ai-chat",
    },
    {
        id: "github-student-pack",
        title: "GitHub Student Developer Pack",
        description: "Free $1,000+ bundle: Copilot, GitHub Pro, Azure credits, JetBrains IDEs, and more. School email or enrollment proof — no US .edu or SSN required.",
        discount: "$1,000+ FREE",
        category: "Tech & AI",
        section: "tech",
        badge: "Must-Have",
        badgeColor: "from-gray-700 to-gray-900",
        logoDomain: "github.com",
        link: "https://education.github.com/pack",
    },
    {
        id: "perplexity-education",
        title: "Perplexity Education Pro",
        description: "Discounted Pro (~$10/mo) with premium models for coursework, job research, and technical writing. SheerID verification; international students welcome.",
        discount: "~$10/mo",
        category: "Tech & AI",
        section: "tech",
        badge: "AI Tool",
        badgeColor: "from-cyan-500 to-blue-600",
        logoDomain: "perplexity.ai",
        link: "https://www.perplexity.ai/students",
    },
    {
        id: "notion-education",
        title: "Notion Education Plus",
        description: "Free Plus plan with unlimited uploads and version history. Organize job apps, visa tracking, and notes. Thousands of global school domains accepted.",
        discount: "FREE Plus",
        category: "Tech & AI",
        section: "tech",
        badge: "Productivity",
        badgeColor: "from-slate-600 to-slate-800",
        logoDomain: "notion.com",
        link: "https://www.notion.com/product/notion-for-education",
    },
    {
        id: "adobe-creative-cloud",
        title: "Adobe Creative Cloud Student",
        description: "Up to 77% off All Apps (~$19.99–$24.99/mo first year). Build portfolios, resumes, and video content. SheerID verification; global students eligible.",
        discount: "Up to 77% OFF",
        category: "Tech & AI",
        section: "tech",
        badge: "Creative",
        badgeColor: "from-red-500 to-rose-600",
        logoDomain: "adobe.com",
        link: "https://www.adobe.com/education/students/creativecloud.html",
    },
    {
        id: "kickresume-student",
        title: "Kickresume Student Premium",
        description: "Full Premium free for up to 6 months. ATS-optimized resume templates and cover letters for OPT/CPT job searches. Verify via ISIC, ITIC, or UNiDAYS.",
        discount: "6 Months FREE",
        category: "Tech & AI",
        section: "tech",
        badge: "Job Search",
        badgeColor: "from-violet-500 to-purple-600",
        logoDomain: "kickresume.com",
        link: "https://www.kickresume.com/en/students",
    },
    {
        id: "microsoft-office-education",
        title: "Microsoft Office 365 Education",
        description: "Free Office 365 Education A1 — web Word, Excel, PowerPoint, OneNote, Teams, and 1 TB OneDrive. Partner-school students with a valid academic email; no credit card or SSN.",
        discount: "FREE",
        category: "Tech & AI",
        section: "tech",
        badge: "Productivity",
        badgeColor: "from-blue-600 to-sky-600",
        logoDomain: "microsoft.com",
        link: "https://www.microsoft.com/en-us/education/products/office",
    },
    {
        id: "google-workspace-free",
        title: "Google Docs, Sheets & Drive",
        description: "Free Docs, Sheets, Slides, and Drive on any Google account. Write resumes, track job applications, and collaborate on coursework without paying for Office or Notion.",
        discount: "FREE",
        category: "Tech & AI",
        section: "tech",
        badge: "Productivity",
        badgeColor: "from-blue-500 to-green-600",
        logoDomain: "google.com",
        link: "https://www.google.com/docs/about/",
    },
    {
        id: "zotero",
        title: "Zotero Reference Manager",
        description: "Fully free, open-source reference manager — citations, PDFs, and bibliographies for theses and grad-school apps. No student verification or SSN; core features permanently free.",
        discount: "FREE",
        category: "Tech & AI",
        section: "tech",
        badge: "Research",
        badgeColor: "from-red-600 to-rose-700",
        logoDomain: "zotero.org",
        link: "https://www.zotero.org/download/",
    },
    {
        id: "photopea",
        title: "Photopea",
        description: "Free browser-based Photoshop alternative with PSD support and advanced editing. Tweak portfolio images and social posts without an Adobe subscription — no install required.",
        discount: "FREE",
        category: "Tech & AI",
        section: "tech",
        badge: "Creative",
        badgeColor: "from-emerald-500 to-teal-600",
        logoDomain: "photopea.com",
        link: "https://www.photopea.com",
    },
    {
        id: "davinci-resolve",
        title: "DaVinci Resolve Free",
        description: "Professional video editing, color correction, and audio tools with no time limit. Build demo reels and project videos without paying for Premiere Pro or Final Cut.",
        discount: "FREE",
        category: "Tech & AI",
        section: "tech",
        badge: "Video",
        badgeColor: "from-gray-700 to-slate-900",
        logoDomain: "blackmagicdesign.com",
        link: "https://www.blackmagicdesign.com/products/davinciresolve",
    },
    {
        id: "spotify-student",
        title: "Spotify Premium Student",
        description: "$6.99/mo bundled with Hulu (With Ads); first month free. Music and TV streaming in one bill for students at Title IV US institutions.",
        discount: "$6.99/mo",
        category: "Lifestyle",
        section: "lifestyle",
        badge: "Bundle",
        badgeColor: "from-green-500 to-emerald-600",
        logoDomain: "spotify.com",
        link: "https://www.spotify.com/us/student/",
    },
    {
        id: "google-gemini-youtube-bundle",
        title: "Google AI + YouTube Premium",
        description: "Up to ~70% off a bundle of Google AI Pro and YouTube Premium for eligible college students. Ad-free YouTube Music plus advanced AI tools in one discounted student price.",
        discount: "~70% OFF Bundle",
        category: "Lifestyle",
        section: "lifestyle",
        badge: "Bundle",
        badgeColor: "from-red-500 to-rose-600",
        logoDomain: "youtube.com",
        link: "https://gemini.google.com/students",
    },
    {
        id: "nordvpn-student",
        title: "NordVPN Student Discount",
        description: "Up to ~76% off 2-year plans plus extra student savings via Student Beans. Secure VPN for banking from home, streaming, and public Wi-Fi — verify as a student, no SSN.",
        discount: "Up to 76% OFF",
        category: "Lifestyle",
        section: "lifestyle",
        badge: "Security",
        badgeColor: "from-slate-600 to-blue-800",
        logoDomain: "nordvpn.com",
        link: "https://www.studentbeans.com/student-discount/us/nordvpn",
    },
    {
        id: "amazon-prime-student",
        title: "Amazon Prime Student",
        description: "6-month free trial, then 50% off Prime at $7.49/mo with free Grubhub+ delivery. Verify with .edu email or age 18–24; no SSN required.",
        discount: "6 Months FREE",
        category: "Lifestyle",
        section: "lifestyle",
        badge: "Student Deal",
        badgeColor: "from-amber-500 to-orange-500",
        logoDomain: "amazon.com",
        link: "https://www.amazon.com/joinstudent",
    },
    {
        id: "unidays",
        title: "UNiDAYS",
        description: "One free signup unlocks 300+ brand discounts — Apple, Uber Eats, Disney+, Nike, Samsung, and more. Accepts many international university domains.",
        discount: "300+ Deals",
        category: "Lifestyle",
        section: "lifestyle",
        badge: "Hub",
        badgeColor: "from-indigo-500 to-purple-600",
        logoDomain: "myunidays.com",
        link: "https://www.myunidays.com",
    },
    {
        id: "libby",
        title: "Libby by OverDrive",
        description: "Free ebooks, audiobooks, and magazines from your public library. Link a library card — great for test prep and language learning without Kindle or Audible costs.",
        discount: "FREE",
        category: "Lifestyle",
        section: "lifestyle",
        badge: "Reading",
        badgeColor: "from-teal-500 to-cyan-600",
        logoDomain: "overdrive.com",
        link: "https://www.overdrive.com/apps/libby",
    },
    {
        id: "tubi",
        title: "Tubi",
        description: "Free ad-supported streaming with a large catalog of movies and TV shows. No student status, payment method, or SSN — just create an account and start watching.",
        discount: "FREE",
        category: "Lifestyle",
        section: "lifestyle",
        badge: "Streaming",
        badgeColor: "from-orange-500 to-amber-600",
        logoDomain: "tubitv.com",
        link: "https://tubitv.com",
    },
    {
        id: "pluto-tv",
        title: "Pluto TV",
        description: "Free ad-supported live TV and on-demand movies and shows. Budget-friendly entertainment for students who can't afford Netflix or Disney+ — no subscription required.",
        discount: "FREE",
        category: "Lifestyle",
        section: "lifestyle",
        badge: "Streaming",
        badgeColor: "from-yellow-500 to-orange-600",
        logoDomain: "pluto.tv",
        link: "https://pluto.tv",
    },
    {
        id: "amazon-freevee",
        title: "Amazon Freevee",
        description: "Free ad-supported streaming from Amazon with movies and TV shows at zero subscription cost. Anyone can sign up — no student verification or payment method needed.",
        discount: "FREE",
        category: "Lifestyle",
        section: "lifestyle",
        badge: "Streaming",
        badgeColor: "from-amber-500 to-orange-500",
        logoDomain: "amazon.com",
        link: "https://www.amazon.com/freevee",
    },
    {
        id: "microsoft-linkedin-bundle",
        title: "Microsoft 365 + LinkedIn Premium",
        description: "Up to 12 months free Microsoft 365 and LinkedIn Premium Career for eligible schools. InMail credits and salary insights for OPT networking.",
        discount: "Up to 12 Mo FREE",
        category: "Career",
        section: "career",
        badge: "Bundle",
        badgeColor: "from-blue-600 to-sky-600",
        logoDomain: "microsoft.com",
        link: "https://www.microsoft.com/en-us/education/products/office",
    },
    {
        id: "linkedin-student-beans",
        title: "LinkedIn Premium (Student Beans)",
        description: "As low as $2.09/mo for extended terms vs $29.99/mo standard. Job insights and messaging tools for the OPT job hunt. International students eligible.",
        discount: "From $2.09/mo",
        category: "Career",
        section: "career",
        badge: "Networking",
        badgeColor: "from-blue-700 to-indigo-700",
        logoDomain: "linkedin.com",
        link: "https://www.studentbeans.com/student-discount/us/linkedin-premium",
    },
    {
        id: "google-ai-career-certificates",
        title: "Google AI Career Certificates",
        description: "Free AI training plus Google Career Certificates for U.S. college students through the Google AI for Education Accelerator. Strengthen your resume for tech, data, and cloud roles.",
        discount: "FREE Training",
        category: "Career",
        section: "career",
        badge: "Certification",
        badgeColor: "from-blue-500 to-green-600",
        logoDomain: "google.com",
        link: "https://blog.google/products-and-platforms/products/gemini/google-ai-pro-students-learning",
    },
    {
        id: "rowzero-scholarship",
        title: "Row Zero $1,000 Scholarship",
        description: "Annual $1,000 scholarship for analytics-focused students (data science, CS, business, engineering) at U.S. or Canadian colleges. Apply with resume and a short essay or video.",
        discount: "$1,000 Award",
        category: "Career",
        section: "career",
        badge: "Scholarship",
        badgeColor: "from-sky-500 to-blue-700",
        logoDomain: "rowzero.com",
        link: "https://rowzero.com/blog/scholarship",
    },
    {
        id: "acm-student",
        title: "ACM Student Membership",
        description: "From $19/year with optional Digital Library access. Research library and networking credentials for CS students — global enrollment, no SSN.",
        discount: "From $19/yr",
        category: "Career",
        section: "career",
        badge: "CS",
        badgeColor: "from-orange-500 to-amber-600",
        logoDomain: "acm.org",
        link: "https://www.acm.org/membership/membership-options",
    },
    {
        id: "ieee-student",
        title: "IEEE Student Membership",
        description: "Around $32/year with discounted IEEE Xplore and conference access. Boosts credibility for engineering and CS students applying to technical roles.",
        discount: "From $32/yr",
        category: "Career",
        section: "career",
        badge: "Engineering",
        badgeColor: "from-blue-500 to-cyan-600",
        logoDomain: "ieee.org",
        link: "https://www.ieee.org/membership",
    },
    {
        id: "princeton-review",
        title: "The Princeton Review",
        description: "Up to $600 off GRE, GMAT, and LSAT courses via ongoing promo codes. Open enrollment — international students welcome, no student ID required.",
        discount: "Up to $600 OFF",
        category: "Career",
        section: "career",
        badge: "Test Prep",
        badgeColor: "from-teal-500 to-emerald-600",
        logoDomain: "princetonreview.com",
        link: "https://www.princetonreview.com/promo",
    },
    {
        id: "kaplan-test-prep",
        title: "Kaplan Test Prep",
        description: "10–15% off GRE, GMAT, and MCAT courses with promo codes. Structured grad-school prep for international applicants — no SSN required.",
        discount: "10–15% OFF",
        category: "Career",
        section: "career",
        badge: "Test Prep",
        badgeColor: "from-emerald-600 to-green-700",
        logoDomain: "kaptest.com",
        link: "https://www.kaptest.com",
    },
    {
        id: "wise-students",
        title: "Wise International Student Account",
        description: "$0 monthly fee with mid-market exchange rates. Receive tuition or family support from abroad without bank markup fees. Passport-based KYC, no US SSN.",
        discount: "$0 Monthly Fee",
        category: "Finance",
        section: "finance",
        badge: "Banking",
        badgeColor: "from-lime-500 to-green-600",
        logoDomain: "wise.com",
        link: "https://wise.com/us/students",
    },
    {
        id: "zolve",
        title: "Zolve US Bank Account",
        description: "No-fee checking plus a credit card with $0 annual fee and merchant discounts. Apply with passport + F-1 visa + I-20 — no SSN or US credit history.",
        discount: "No Annual Fee",
        category: "Finance",
        section: "finance",
        badge: "New Arrivals",
        badgeColor: "from-fuchsia-500 to-pink-600",
        logoDomain: "zolve.com",
        link: "https://zolve.com",
    },
    {
        id: "remitly",
        title: "Remitly Money Transfer",
        description: "Discounted or fee-free first transfer for new users. Low-cost alternative to bank wires for sending earnings home or receiving family support.",
        discount: "First Transfer Deal",
        category: "Finance",
        section: "finance",
        badge: "Remittance",
        badgeColor: "from-sky-500 to-blue-600",
        logoDomain: "remitly.com",
        link: "https://www.remitly.com",
    },
    {
        id: "uhaul-collegeboxes",
        title: "U-Haul Collegeboxes",
        description: "No registration fee, up to 40% off shipping, plus periodic free self-storage offers. For students moving between dorms, internships, or after OPT placement.",
        discount: "Up to 40% OFF",
        category: "Finance",
        section: "finance",
        badge: "Moving",
        badgeColor: "from-orange-500 to-red-500",
        logoDomain: "uhaul.com",
        link: "https://www.uhaul.com/Discounts/",
    },
    {
        id: "isi-insurance",
        title: "ISI Student Insurance",
        description: "Affordable student health coverage with United Healthcare network and 24/7 telemedicine.",
        discount: "From $35/mo",
        category: "Health Insurance",
        section: "essential",
        badge: "Best Value",
        badgeColor: "from-green-500 to-emerald-500",
        logoDomain: "internationalstudentinsurance.com",
        link: "https://www.internationalstudentinsurance.com/?Trackmyopt",
    },
    {
        id: "sprintax",
        title: "Sprintax Tax Filing",
        description: "Partner coupon for all users. The #1 tax software for international students on F-1/OPT — get your code in Tax Filing.",
        discount: "$20 value",
        category: "Tax Services",
        section: "essential",
        badge: "Tax Season",
        badgeColor: "from-emerald-500 to-teal-500",
        logoDomain: "sprintax.com",
        link: "/dashboard/tax-filing",
    },
    {
        id: "chrome-extension",
        title: "Chrome Extension",
        description: "Quick access to your OPT countdown and case status right from your browser.",
        discount: "FREE",
        category: "Tools",
        section: "essential",
        badge: "New",
        badgeColor: "from-cyan-500 to-blue-500",
        logoDomain: "trackmyopt.com",
        link: "https://chromewebstore.google.com/detail/hfljbefkccdmlnhclfojlafipjnjbajm?utm_source=item-share-cb",
    },
];

export function getCatalogSavings(offers: Offer[], fuelDeals: FuelDeal[]) {
    const offerTotal = offers.reduce((sum, offer) => sum + (ESTIMATED_SAVINGS_USD[offer.id] ?? 0), 0);
    const fuelTotal = fuelDeals.reduce((sum, deal) => sum + (ESTIMATED_SAVINGS_USD[deal.id] ?? 0), 0);
    return {
        totalUsd: offerTotal + fuelTotal,
        dealCount: offers.length + fuelDeals.length,
    };
}
