const fs=require('fs'),path=require('path');const out=path.resolve(__dirname,'..'),comp=path.join(out,'composition'),assets=path.join(comp,'assets');
for(const name of ['gsap.min.js','icon128.png','click.ogg'])fs.copyFileSync(path.join('brag-output/composition/assets',name),path.join(assets,name));
fs.copyFileSync('.agents/skills/brag/assets/music/happy-beats-business-moves-vol-1-by-ende-dot-app.mp3',path.join(assets,'music.mp3'));
fs.copyFileSync('.agents/skills/brag/assets/music/cues/happy-beats-business-moves-vol-1-by-ende-dot-app.music-cues.json',path.join(assets,'music-cues.json'));
const captures=Object.fromEntries(JSON.parse(fs.readFileSync(path.join(out,'capture-manifest.json'))).map(x=>[x.name,x]));
const scenes=[];
function s(image,duration,chapter,title,body,action,crop,click=false,note='Demo account · Fictional data'){scenes.push({image,duration,chapter,title,body,action,crop,click,note});}
const popup=[0,0,360,520],home=[0,0,360,443],form=[0,0,360,440],job=[0,0,1000,680];
s('job-before',1.4,'APPLICATION TOOLS','Fill the form.','Click Prefill this application.','Your profile → the open application',job,true);
s('job-filled',3.6,'APPLICATION TOOLS','Review the result.','Your contact details are filled. You choose when to submit.','Prefill → review',job);
s('home',5,'EXTENSION POPUP','Start here.','Open TrackMyOPT from Chrome’s toolbar. Find all four OPT tools together.','Chrome toolbar → TrackMyOPT → OPT Tools',home,true);
s('opt-clock-empty',2,'01 / OPT CLOCK','Open OPT Clock.','Enter the start date printed on your OPT EAD.','OPT Tools → OPT Clock',form,true);
s('opt-calendar',2,'01 / OPT CLOCK','Choose your date.','Type the date or use the calendar.','OPT EAD start date',[0,60,360,570]);
s('opt-clock-filled',3,'01 / OPT CLOCK','Save & Go.','The example starts on September 6. Click to open the tracker.','OPT EAD start date → Save & Go',form,true);
s('opt-clock-result',6,'01 / OPT CLOCK','See your clock.','The tracker shows days used and days remaining.','Saved date → employment timeline',popup);
s('opt-reminders',5,'01 / OPT CLOCK','Keep reminders on.','Daily email reminders sit below the clock. Edit the address or stop reminders here.','Scroll down → Daily reminders',[0,420,360,230],false,'Demo account · Reminder features depend on plan');
s('stem-clock-nav',3,'02 / STEM CLOCK','Find STEM Clock.','Return to OPT Tools and choose STEM Clock.','OPT Tools → STEM Clock',home,true);
s('stem-clock-empty',2,'02 / STEM CLOCK','Use your STEM date.','Enter the start date on your STEM OPT EAD.','STEM EAD start date',form,true);
s('stem-clock-filled',3,'02 / STEM CLOCK','Save & Go.','Save the date to open the STEM tracker.','STEM EAD start date → Save & Go',form,true);
s('stem-clock-result',6,'02 / STEM CLOCK','Read the STEM clock.','View cumulative unemployment days used and remaining.','Saved date → STEM employment timeline',popup);
s('opt-filing-nav',3,'03 / OPT APPLY DATES','Find your window.','Back in OPT Tools, select OPT Apply Dates.','OPT Tools → OPT Apply Dates',home,true);
s('opt-filing-empty',2,'03 / OPT APPLY DATES','Enter your dates.','Start with your program end date.','Program end date + DSO recommendation',form,true);
s('opt-filing-filled',3,'03 / OPT APPLY DATES','Calculate the window.','Add the DSO recommendation date when available. Then calculate.','Dates → Calculate Filing Window',form,true);
s('opt-filing-result',6,'03 / OPT APPLY DATES','See the deadline.','Read the opening date, deadline, and countdown. Use Modify dates to update them.','Filing window → countdown',popup);
s('stem-filing-nav',3,'04 / STEM APPLY DATES','Plan the extension.','Choose STEM Apply Dates from OPT Tools.','OPT Tools → STEM Apply Dates',home,true);
s('stem-filing-empty',2,'04 / STEM APPLY DATES','Enter the expiry date.','Use the end date on your current OPT EAD.','Current OPT expires',form,true);
s('stem-filing-filled',3,'04 / STEM APPLY DATES','Add the recommendation.','Enter the STEM recommendation date, then calculate.','Dates → Calculate Filing Window',form,true);
s('stem-filing-result',6,'04 / STEM APPLY DATES','Read the STEM window.','The result shows the filing window and time left.','Filing window → countdown',popup);
s('home',4,'CASE STATUS','Check at a glance.','Your case-status card appears above OPT Tools. Open it for the dashboard.','Extension popup → Case status',[0,0,360,205],false,'Demo case · Follow official guidance and your DSO');
s('job-before',3,'05 / JOB APPLICATIONS','Open an application.','The job assistant sits beside the application form.','Job posting → TrackMyOPT sidebar',job,true);
s('job-filled',4,'05 / JOB APPLICATIONS','Prefill. Then review.','Profile fields fill from saved data. Existing answers stay in place.','You review and submit the application',job);
s('job-save',4,'05 / JOB APPLICATIONS','Read the posting signal.','The sponsorship badge summarizes what the posting says. This sample does not state sponsorship.','Job posting → sponsorship signal',[620,75,375,145],false,'Posting language is not a sponsorship guarantee');
s('job-save',3,'06 / JOB TRACKER','Save this role.','Click Save to job tracker.','Sidebar → Save to job tracker',[620,12,375,315],true);
s('job-status',4,'06 / JOB TRACKER','Choose the status.','Not applied yet? Save to Wishlist. Already applied? Select I applied.','Application Status → Wishlist or Applied',[309,219,382,244],[500,340]);
s('job-saved',4,'06 / JOB TRACKER','The job is saved.','The badge changes to Wishlist. View in tracker opens your dashboard.','Wishlist → View in tracker',[620,12,375,335]);
s('job-analyze',3,'07 / RESUME ANALYSIS','Analyze the posting.','Click Analyze with AI to compare your saved résumé with this job.','Sidebar → Analyze with AI',[620,310,375,320],true,'Illustrative AI workflow · Plan limits apply');
s('job-analysis',5,'07 / RESUME ANALYSIS','Review keyword gaps.','See matched and missing keywords. Add experience only when it is accurate.','Analyze with AI → keyword review',[320,333,360,215],false,'Illustrative analysis output · No hiring outcome promised');
s('job-resume',3,'08 / TAILORED RÉSUMÉ','Open résumé tools.','Click Generate custom resume.','Sidebar → Generate custom resume',[620,320,375,310],true);
s('sidepanel-top',4,'08 / TAILORED RÉSUMÉ','Check the job details.','The Chrome side panel keeps the job and résumé controls together.','Side panel → Job description',[0,0,400,535]);
s('sidepanel-create',4,'08 / TAILORED RÉSUMÉ','Choose your source.','Select a saved résumé, or paste or upload one. Choose a template and create.','Résumé + template → Create tailored résumé',[0,160,400,405],true,'Demo account · AI features have plan limits');
s('sidepanel-running',3,'08 / TAILORED RÉSUMÉ','Follow the progress.','Watch the tailoring and PDF steps in the side panel.','Create → progress',[0,365,400,330],false,'Illustrative service response · Wait time shortened');
s('sidepanel-result',5,'08 / TAILORED RÉSUMÉ','Review your résumé.','Download the PDF or open it in the editor.','Done → Download PDF / Open in editor',[0,215,400,433],false,'Illustrative service response · Review before use');
s('resume-ready',3,'09 / COVER LETTER','More résumé tools.','The in-page résumé workflow also provides cover-letter controls.','In-page résumé result → Generate cover letter',[620,325,375,290],false,'In-page workflow · Illustrative service response');
s('cover-letter',6,'09 / COVER LETTER','Review and edit.','Generate a cover letter, then edit the draft before using it.','Cover letter → Edit → Save',[620,290,375,335],false,'Illustrative draft · Verify every statement');
s('private-answers',6,'10 / SAVED ANSWERS','Keep answers together.','Open Private answers to find Manage saved prefill data.','Sidebar → Private answers',[625,180,360,220],false,'Demo account · Review matching answers before submitting');
s('home-settings',4,'11 / PREFILL SETTINGS','Choose your workflow.','The popup contains prefill mode and skills settings.','Popup → Job application → Prefill mode',[0,0,360,650]);
s('continuous',4,'11 / PREFILL SETTINGS','Continuous mode.','Switch from Step-by-step to Continuous.','Prefill mode → Continuous',[0,275,360,256],false,'Demo Pro account · Availability depends on plan');
s('guided',5,'11 / PREFILL SETTINGS','Guided Autopilot.','Enable safe step navigation. Review the application before submitting.','Guided Autopilot → enabled',[0,275,360,256],false,'Demo Pro account · Guided Autopilot never clicks Submit');
s('widget-settings',5,'12 / SIDEBAR SETTINGS','Make it fit your flow.','Use Settings to choose whether the sidebar starts expanded or minimized.','Sidebar → Settings',[620,10,375,180]);
s('home',6,'TRACKMYOPT FOR CHROME','Your OPT tools.\nYour job tools.','Explore TrackMyOPT from the Chrome Web Store.','trackmyopt.com',home,false,'Demo data · Confirm immigration guidance with your DSO');
let total=0;for(const scene of scenes){scene.start=total;total+=scene.duration;}
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const timeline=[],clicks=[];
const sections=scenes.map((q,i)=>{const m=captures[q.image];if(!m)throw Error('Missing capture '+q.image);const [cx,cy,cw,ch]=q.crop;const full=cw>800;const maxW=full?1240:815,maxH=810;const scale=Math.min(maxW/cw,maxH/ch),w=cw*scale,h=ch*scale;const x=full?620:1005+(815-w)/2,y=154+(810-h)/2;const target=Array.isArray(q.click)?{x:q.click[0],y:q.click[1]}:q.click?m.target:null;const clickAt=q.start+q.duration-.16;const cursor=target?`<div class="hf-simulated-cursor" id="cursor${i}"><div class="hf-simulated-cursor-pulse" id="pulse${i}"></div><svg viewBox="0 0 24 24"><path d="M3 2.8 20.6 14 12.8 15.5 9 22 3 2.8Z" fill="#0f172a" stroke="white" stroke-width="1.5"/></svg></div>`:'';
if(target){const tx=x+(target.x-cx)*scale-6,ty=y+(target.y-cy)*scale-6;timeline.push(`tl.fromTo('#cursor${i}',{x:${tx+75},y:${ty+85},opacity:0},{x:${tx},y:${ty},opacity:1,duration:.65,ease:'power2.out'},${Math.max(q.start+.15,clickAt-.9)});tl.fromTo('#pulse${i}',{scale:.2,opacity:.75},{scale:2.4,opacity:0,duration:.32,ease:'power2.out'},${clickAt});`);clicks.push(clickAt);}
// Hard cuts preserve exact before/after interaction; chapter starts slide the caption only.
timeline.push(`tl.fromTo('#copy${i}',{y:12,opacity:1},{y:0,opacity:1,duration:.25,ease:'power2.out'},${q.start});`);
return `<section class="clip" id="scene${i}" data-start="${q.start}" data-duration="${q.duration}" data-track-index="1"><div class="scene"><div class="copy ${full?'compact':''}" id="copy${i}"><p class="chapter">${esc(q.chapter)}</p><h1>${esc(q.title).replaceAll('\n','<br>')}</h1><p class="description">${esc(q.body)}</p><div class="action"><span>FOLLOW THE CLICKS</span>${esc(q.action)}</div></div><div class="capture" style="left:${x}px;top:${y}px;width:${w}px;height:${h}px"><img data-layout-allow-overflow="true" src="assets/${q.image}.png" alt="Actual TrackMyOPT interface: ${esc(q.action)}" style="width:${m.width*scale}px;height:${m.height*scale}px;left:${-cx*scale}px;top:${-cy*scale}px"></div>${cursor}<div class="note">${esc(q.note)}</div><div class="number">${String(i+1).padStart(2,'0')} / ${scenes.length}</div></div></section>`;}).join('\n');
const automation=esc(JSON.stringify({version:1,lanes:[{target:'volume',points:[{t:0,v:0},{t:.5,v:.22},{t:total-2,v:.22},{t:total,v:0}]}]}));
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=1920,height=1080"><title>TrackMyOPT — Chrome extension walkthrough</title><script src="assets/gsap.min.js"></script><style>
*{box-sizing:border-box}html,body{margin:0;width:1920px;height:1080px;overflow:hidden;background:#f6f8fb;font-family:system-ui,sans-serif;color:#0f172a}#root{width:100%;height:100%;position:relative;overflow:hidden}.brand{position:absolute;top:47px;left:72px;display:flex;align-items:center;gap:18px;font-size:32px;font-weight:720;z-index:3}.brand img{height:54px;width:54px;border-radius:13px}.brand span{font-size:21px;color:#475569;font-weight:500;margin-left:20px}.rule{position:absolute;left:72px;right:72px;top:124px;height:2px;background:#dce3ee}.clip,.scene{position:absolute;inset:0}.scene{background:transparent}.copy{position:absolute;left:76px;top:223px;width:790px}.copy.compact{width:475px;top:210px}.chapter{color:#1e40af;letter-spacing:2.4px;font-size:23px;font-weight:650;margin:0 0 28px}h1{font-size:76px;font-weight:650;letter-spacing:-3px;line-height:1.08;margin:0 0 35px;white-space:normal}.compact h1{font-size:64px}.description{font-size:34px;line-height:1.4;color:#475569;margin:0;max-width:700px}.compact .description{font-size:29px}.action{font-size:29px;line-height:1.4;margin-top:48px;padding:23px 0 0;border-top:3px solid #2563eb;color:#1e40af;max-width:730px}.action span{display:block;font-size:18px;letter-spacing:2px;color:#475569;font-weight:650;margin-bottom:11px}.capture{position:absolute;overflow:hidden;border:2px solid #dce3ee;border-radius:22px;background:#f6f8fb;box-shadow:0 16px 48px rgba(15,23,42,.1)}.capture img{position:absolute;max-width:none}.note{position:absolute;left:76px;bottom:38px;font-size:23px;color:#475569}.number{position:absolute;right:72px;bottom:38px;font-size:21px;color:#475569}.progress{position:absolute;left:0;bottom:0;height:6px;width:100%;background:#2563eb;transform-origin:left center;z-index:6}.hf-simulated-cursor{position:absolute;left:0;top:0;width:44px;height:44px;pointer-events:none;z-index:9;opacity:0}.hf-simulated-cursor svg{width:100%;height:100%}.hf-simulated-cursor-pulse{position:absolute;left:-15px;top:-15px;width:40px;height:40px;border:3px solid #2563eb;border-radius:50%;opacity:0}
</style></head><body><div id="root" data-composition-id="main" data-width="1920" data-height="1080" data-duration="${total}"><div class="brand"><img src="assets/icon128.png" alt="TrackMyOPT logo">TrackMyOPT<span>Chrome extension · Product walkthrough</span></div><div class="rule"></div>${sections}<div class="progress" id="progress"></div><audio id="music" src="assets/music.mp3" data-start="0" data-duration="${total}" data-track-index="3" data-volume=".22" data-automation="${automation}"></audio>${clicks.map((t,i)=>`<audio id="click${i}" src="assets/click.ogg" data-start="${t}" data-duration=".04" data-track-index="4" data-volume=".45"></audio>`).join('')}</div><script>const tl=gsap.timeline({paused:true});${timeline.join('\n')}tl.fromTo('#progress',{scaleX:0},{scaleX:1,duration:${total},ease:'none'},0);window.__timelines=window.__timelines||{};window.__timelines.main=tl;</script></body></html>`;
fs.writeFileSync(path.join(comp,'index.html'),html);fs.writeFileSync(path.join(out,'storyboard.json'),JSON.stringify({width:1920,height:1080,fps:30,duration:total,scenes},null,2));
fs.writeFileSync(path.join(out,'brag-plan.md'),`# TrackMyOPT Chrome Web Store walkthrough\n\nA ${total}-second, 1920 × 1080 product demo. This replaces the earlier 20-second vertical brief because the owner requested an entire click-by-click extension walkthrough for the store listing.\n\n## Product and creative decisions\n\n1. Product: TrackMyOPT Chrome extension, with OPT/STEM tools and job-application assistance.\n2. Audience: prospective extension users who need to see where controls are and what they do.\n3. Strongest benefit: use saved profile data on an application while keeping review and submission in the user's hands.\n4. Hook: real Prefill click and filled form within 1.4 seconds.\n5. Proof: source-rendered popup, clocks, calculators, sidebar, dialogs, and Chrome side panel.\n6. Features: four OPT tools, reminders, case status, prefill, saved answers, job saving, AI keyword analysis, résumé workflow, cover-letter editing, modes and sidebar settings.\n7. Branding: repository logo, blue #2563eb, navy #0f172a, background #f6f8fb, native system typography. Source screen styling is retained.\n8. Tone: polished, practical product walkthrough; explicit action/result captions.\n9. Destination: YouTube video URL in the Chrome Web Store listing; no store submission in this task.\n\n## Music cue guidance\n\nBundled Happy Beats Business Moves vol. 1 by ende.app; 163.96 seconds, 120.19 BPM. Cue preset shipped with composition. Interaction/readability determines edits; no voice or generated music. Soft fade-in/out, understated click cues. No rendered speed or performance claims: service waits are explicitly shortened.\n\n## Storyboard\n\n| Time | Chapter | Real screen | Caption / action |\n|---|---|---|---|\n${scenes.map(q=>`| ${q.start.toFixed(1)}–${(q.start+q.duration).toFixed(1)} | ${q.chapter} | ${q.image} | ${q.title.replaceAll('\n',' ')} ${q.action} |`).join('\n')}\n\n## Fidelity and boundaries\n\nCapture scripts bundle the actual repository extension components. A local harness supplies fictional profile, account, calculator, tracker and AI-service responses; no account, applicant data, or production endpoint is accessed. Prefill is executed by the actual runPrefill engine. Calendar and date calculations run in the product code. UI state captures are held and edited for readability, not a continuous screen recording. AI numeric score is cropped out; no invented performance metric appears. Source generation wait times are shortened and labeled. Résumé side panel is the current Chrome route; cover-letter controls demonstrate the separate in-page résumé workflow. No app source changes.\n`);
console.log('Built',scenes.length,'scenes,',total,'seconds.');
