-- Tailored resumes the extension generated for a specific job posting.
--
-- Before this table an artifact lived only in chrome.storage.session: one slot
-- for the whole browser, cleared on restart, expiring after 30 minutes. A user
-- who generated a resume, read the posting, and then applied had nothing left
-- to attach. Persisting per job makes "generate now, apply later" work, and
-- makes the tailored resume available from any device the user is signed in on.
--
-- Server API only. The extension reaches this table exclusively through
-- /api/extension/resume-artifact, which authenticates first and matches the
-- requested page against `source_url` using the same ATS job-identity rules the
-- extension itself uses, so both sides can never disagree about which resume
-- belongs to which posting.

CREATE TABLE IF NOT EXISTS public.generated_resume_artifacts (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Job identity. source_url is authoritative for matching; the ats_* columns
  -- are the parsed form, denormalized so a lookup can shortlist candidates
  -- without deserializing every stored PDF.
  source_url             text NOT NULL CHECK (char_length(source_url) <= 2048),
  ats_platform           text CHECK (char_length(ats_platform) <= 40),
  ats_tenant             text CHECK (char_length(ats_tenant) <= 200),
  ats_job_id             text CHECK (char_length(ats_job_id) <= 200),
  requisition_id         text CHECK (char_length(requisition_id) <= 200),
  company_name           text NOT NULL DEFAULT '' CHECK (char_length(company_name) <= 300),
  role_title             text NOT NULL DEFAULT '' CHECK (char_length(role_title) <= 300),

  -- The complete GeneratedResumeArtifactV1, PDF bytes included. Kept as one
  -- document so the extension receives back exactly what it stored and no
  -- reassembly step can corrupt the hash it verifies against.
  artifact               jsonb NOT NULL,
  generated_content_hash text NOT NULL CHECK (generated_content_hash ~ '^[0-9a-f]{64}$'),
  pdf_sha256             text NOT NULL CHECK (pdf_sha256 ~ '^[0-9a-f]{64}$'),

  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),
  expires_at             timestamptz NOT NULL
);

COMMENT ON TABLE public.generated_resume_artifacts IS
  'Per-job tailored resumes generated by the Chrome extension. Server API only.';
COMMENT ON COLUMN public.generated_resume_artifacts.source_url IS
  'Posting URL at generation time. Matching uses the shared ATS job-identity rules, not string equality.';
COMMENT ON COLUMN public.generated_resume_artifacts.artifact IS
  'Full GeneratedResumeArtifactV1 including the compiled PDF as base64.';

-- Lookup path: newest non-expired artifacts for this user, identity columns only.
CREATE INDEX IF NOT EXISTS generated_resume_artifacts_user_recent_idx
  ON public.generated_resume_artifacts (user_id, created_at DESC);

-- Fast shortlist when the page resolves to a known ATS posting.
CREATE INDEX IF NOT EXISTS generated_resume_artifacts_ats_idx
  ON public.generated_resume_artifacts (user_id, ats_platform, ats_job_id)
  WHERE ats_job_id IS NOT NULL;

ALTER TABLE public.generated_resume_artifacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.generated_resume_artifacts FORCE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS trg_generated_resume_artifacts_updated_at
  ON public.generated_resume_artifacts;
CREATE TRIGGER trg_generated_resume_artifacts_updated_at
  BEFORE UPDATE ON public.generated_resume_artifacts
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

REVOKE ALL ON public.generated_resume_artifacts FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.generated_resume_artifacts TO service_role;
