CREATE TABLE IF NOT EXISTS public.ai_generation_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  generation_kind text NOT NULL CHECK (generation_kind IN ('screening_answer', 'cover_letter')),
  item_hash char(64) NOT NULL CHECK (item_hash ~ '^[a-f0-9]{64}$'),
  generation_day date NOT NULL DEFAULT ((now() AT TIME ZONE 'UTC')::date),
  is_regeneration boolean NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_generation_events_user_day
  ON public.ai_generation_events (user_id, generation_day, created_at);
CREATE INDEX IF NOT EXISTS idx_ai_generation_events_item_day
  ON public.ai_generation_events (user_id, generation_kind, item_hash, generation_day);

ALTER TABLE public.ai_generation_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ai_generation_events FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.ai_generation_events TO service_role;

CREATE OR REPLACE FUNCTION public.reserve_ai_generation(
  p_user_id uuid,
  p_generation_kind text,
  p_item_hash text,
  p_daily_limit integer DEFAULT 25,
  p_item_regeneration_limit integer DEFAULT 3,
  p_short_window_limit integer DEFAULT 6
)
RETURNS TABLE (
  allowed boolean,
  daily_limit integer,
  daily_remaining integer,
  item_regeneration_limit integer,
  item_regenerations_remaining integer,
  resets_at timestamptz,
  error text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_day date := (now() AT TIME ZONE 'UTC')::date;
  v_reset timestamptz := ((date_trunc('day', now() AT TIME ZONE 'UTC') + interval '1 day') AT TIME ZONE 'UTC');
  v_daily_count integer;
  v_item_count integer;
  v_short_count integer;
  v_regenerations_used integer;
BEGIN
  IF p_user_id IS NULL
    OR p_generation_kind NOT IN ('screening_answer', 'cover_letter')
    OR p_item_hash !~ '^[a-f0-9]{64}$'
    OR p_daily_limit < 1
    OR p_item_regeneration_limit < 0
    OR p_short_window_limit < 1 THEN
    RAISE EXCEPTION 'invalid ai generation reservation';
  END IF;

  PERFORM pg_advisory_xact_lock(
    hashtextextended(p_user_id::text || ':' || v_day::text, 0)
  );

  SELECT count(*)::integer INTO v_daily_count
  FROM public.ai_generation_events
  WHERE user_id = p_user_id AND generation_day = v_day;

  SELECT count(*)::integer INTO v_item_count
  FROM public.ai_generation_events
  WHERE user_id = p_user_id
    AND generation_kind = p_generation_kind
    AND item_hash = p_item_hash
    AND generation_day = v_day;
  v_regenerations_used := greatest(v_item_count - 1, 0);

  SELECT count(*)::integer INTO v_short_count
  FROM public.ai_generation_events
  WHERE user_id = p_user_id AND created_at > now() - interval '1 minute';

  IF v_daily_count >= p_daily_limit THEN
    RETURN QUERY SELECT false, p_daily_limit, 0,
      p_item_regeneration_limit,
      greatest(0, p_item_regeneration_limit - v_regenerations_used),
      v_reset, 'ai_daily_limit_reached'::text;
    RETURN;
  END IF;

  IF v_item_count > 0 AND v_regenerations_used >= p_item_regeneration_limit THEN
    RETURN QUERY SELECT false, p_daily_limit,
      greatest(0, p_daily_limit - v_daily_count),
      p_item_regeneration_limit, 0, v_reset,
      'ai_item_regeneration_limit_reached'::text;
    RETURN;
  END IF;

  IF v_short_count >= p_short_window_limit THEN
    RETURN QUERY SELECT false, p_daily_limit,
      greatest(0, p_daily_limit - v_daily_count),
      p_item_regeneration_limit,
      greatest(0, p_item_regeneration_limit - v_regenerations_used),
      v_reset, 'ai_rate_limited'::text;
    RETURN;
  END IF;

  INSERT INTO public.ai_generation_events (
    user_id, generation_kind, item_hash, generation_day, is_regeneration
  ) VALUES (
    p_user_id, p_generation_kind, p_item_hash, v_day, v_item_count > 0
  );

  RETURN QUERY SELECT true, p_daily_limit,
    greatest(0, p_daily_limit - v_daily_count - 1),
    p_item_regeneration_limit,
    greatest(0, p_item_regeneration_limit - v_item_count),
    v_reset, NULL::text;
END;
$$;

REVOKE ALL ON FUNCTION public.reserve_ai_generation(uuid, text, text, integer, integer, integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.reserve_ai_generation(uuid, text, text, integer, integer, integer)
  TO service_role;
